apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game-2048
          image: alexwhen/docker-2048:latest
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
