apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app2048
  name: app2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        name: app2048
        ports:
        - containerPort: 80