---
- hosts: kubernetes-master-nodes
  become: yes
  vars_files:
  - env_variables 
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull


  - name: Initializing Kubernetes cluster
    shell: kubeadm init --upload-certs --control-plane-endpoint manager:6443 --pod-network-cidr=10.244.0.0/16
    register: output

  - name: Copying required files
    shell: |
     modprobe overlay
     modprobe br_netfilter
     rm /etc/containerd/config.toml
     systemctl restart containerd
     export KUBECONFIG=/etc/kubernetes/admin.conf

  - name: Create .kube directory
    command: mkdir -p /home/azureuser/.kube

  - name: Copy admin.conf to .kube/config
    command: sudo cp -i /etc/kubernetes/admin.conf /home/azureuser/.kube/config

  - name: Set ownership of .kube/config
    file:
      path: /home/azureuser/.kube/config
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: file

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Install Calico CNI
    become: yes
    become_user: azureuser
    shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
    args:
      chdir: /home/azureuser
    when: "'manager' in inventory_hostname"


  - name: Get join token
    become: yes
    become_user: azureuser
    shell: sudo kubeadm token create  --print-join-command
    register: kubernetes_join_command

  - name: Copy join command to local file.
    become: yes
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
