---
- hosts: all
  become: yes
  vars_files:
  - env_variables 
  tasks:
  - name: Add hostname and IP address to /etc/hosts file
    lineinfile:
      dest: /etc/hosts
      line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
      state: present
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Ajouter le dépôt YUM de Docker
    yum_repository:
      name: Docker
      description: Docker Repository
      baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Remove existing kubelet package
    yum:
      name: kubelet
      state: absent
  - name: Install Containerd
    yum:
      name: containerd.io
      state: present
  - name: Create Containerd directory
    file:
      path: /etc/containerd
      state: directory

  - name: Add Containerd configuration
    command: /usr/bin/containerd config default > /etc/containerd/config.toml       
    ignore_errors: yes
  
  - name: Configure systemd cgroup driver for Containerd
    lineinfile:
      path: /etc/containerd/config.toml
      regexp: '            SystemdCgroup = false'
      line: '            SystemdCgroup = true'

  - name: Enable and start Containerd service
    systemd:
      name: containerd
      state: restarted
      enabled: yes
      daemon_reload: yes
  - name: Uncomment disabled_plugins line and remove cri from the list
    lineinfile:
      path: /etc/containerd/config.toml
      regexp: '^disabled_plugins\s*='
      line: 'disabled_plugins = []'

  - name: Load br_netfilter kernel module
    modprobe:
      name: br_netfilter
      state: present

  - name: Ensure br_netfilter module is loaded at boot
    lineinfile:
      dest: /etc/modules-load.d/br_netfilter.conf
      line: 'br_netfilter'
      create: true

  - name: Enable bridge-nf-call-iptables
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

  - name: Enable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present

  - name: Apply sysctl changes
    command: sysctl -p

  - name: Restart Containerd service
    service:
      name: containerd
      state: restarted
  - name: Installing required packages
    yum:
     name: "{{ item }}"
     state: present
    with_items: "{{ packages }}"
      
  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: Install tc
    yum:
      name: iproute-tc
      state: present
  
  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

